name: databricks-cicd

on:
 push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run a databricks notebook
        env:
          GITBRANCH: "main"
          DBCLIPATH: "/usr/local/bin"
	  JQPATH: "/usr/bin"
	  JOBPREFIX: "db"
	  BUNDLETARGET: "dev"
      - name: Check out repository
        uses: actions/checkout@v3
      # Install databricks CLI 

      - name: Install databricks CLI
	    run: sudo apt-get update
		run: sudo apt install plocate -y
		run: sudo apt-get install unzip -y
		run: sudo apt-get install openjdk-17-jre -y
		run: sudo apt-get install junit -y
		run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  
		run: sudo apt-get install jq -y
		run: sudo apt install pip -y
		run: pip install --upgrade wheel
		
      - name: Databricks CLI version
        run: databricks --version
     
      - name: Run a databricks notebook
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        uses: databricks/run-notebook@v0.0.3
        with:
          local-notebook-path: .github/workflows/dabdemo_notebook.py
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m5d.large"
           }

      
      
