name: databricks-cicd

on:
 push:
runs-on: self-hosted
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # Install databricks CLI 
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

      - name: Databricks CLI version
        run: databricks --version
     
      - name: Run a databricks notebook
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        uses: databricks/run-notebook@v0.0.3
        with:
          local-notebook-path: .github/workflows/dev
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m5d.large"
           }

      
      
